#!/bin/bash

cp -r ~/.config/i3/* ~/Dropbox/Miscellaneous/Filedump/i3
cp -r ~/.scripts/* ~/Dropbox/Miscellaneous/Filedump/scripts
cp ~/.vimrc ~/Dropbox/Miscellaneous/Filedump/Vim/vimrcUbuntu
cp ~/.bashrc ~/Dropbox/Miscellaneous/Filedump/
cp -r ~/.config/ranger/* ~/Dropbox/Miscellaneous/Filedump/Ranger
cp ~/.config/dunst/dunstrc ~/Dropbox/Miscellaneous/Filedump/dunst

cp -r ~/.scripts/* ~/Documents/Repositories/Dotfiles/.scripts
