#!/bin/bash

SETUP=false
OFF=false

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -s|--setup)
      SETUP=true
      shift
      ;;
    -o|--off)
      OFF=true
      shift
      ;;
    *) # unknown
      shift
      ;;
  esac
done

if $OFF; then
  xrandr --output DP1-1 --off ; xrandr --output DP1-2 --off
  exit 0
fi

if $SETUP; then
  xrandr --output DP1-1 --auto --right-of eDP1 ; xrandr --output DP1-2 --auto --right-of DP1-1
fi
