#!/bin/bash
KEY_LAYOUT=$(~/.scripts/key_layout)

if [ $KEY_LAYOUT = "DE" ]; then
  setxkbmap gb
  ~/.scripts/notify/notify "Layout" "GB"
else
  setxkbmap de
  ~/.scripts/notify/notify "Layout" "DE"
fi
